CREATE TABLE articles (
  id INT AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOT NULL,
  content LONGTEXT NOT NULL,
  dateAdded DATETIME NOT NULL,
  authorId INT NOT NULL,
  image VARCHAR(255) NOT NULL,
  viewCount INT NOT NULL,
  INDEX IDX_BFDD3168A196F9FD (authorId),
  PRIMARY KEY(id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE comments (
  id INT AUTO_INCREMENT NOT NULL,
  article_id INT DEFAULT NULL,
  author_id INT DEFAULT NULL,
  content LONGTEXT NOT NULL,
  dateAdded DATETIME NOT NULL,
  INDEX IDX_5F9E962A7294869C (article_id),
  INDEX IDX_5F9E962AF675F31B (author_id),
  PRIMARY KEY(id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE messages (
  id INT AUTO_INCREMENT NOT NULL,
  sender_id INT NOT NULL,
  recipient_id INT DEFAULT NULL,
  about VARCHAR(255) NOT NULL,
  content LONGTEXT NOT NULL,
  dateAdded DATETIME NOT NULL,
  isReaded TINYINT(1) NOT NULL,
  INDEX IDX_DB021E96F624B39D (sender_id),
  INDEX IDX_DB021E96E92F8F78 (recipient_id),
  PRIMARY KEY(id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE roles (
  id INT AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  UNIQUE INDEX UNIQ_B63E2EC75E237E06 (name),
  PRIMARY KEY(id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email),
  PRIMARY KEY(id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE users_roles (
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  INDEX IDX_51498A8EA76ED395 (user_id),
  INDEX IDX_51498A8ED60322AC (role_id),
  PRIMARY KEY(user_id, role_id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE articles ADD CONSTRAINT FK_BFDD3168A196F9FD FOREIGN KEY (authorId) REFERENCES users (id);
ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A7294869C FOREIGN KEY (article_id) REFERENCES articles (id);
ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AF675F31B FOREIGN KEY (author_id) REFERENCES users (id);
ALTER TABLE messages ADD CONSTRAINT FK_DB021E96F624B39D FOREIGN KEY (sender_id) REFERENCES users (id);
ALTER TABLE messages ADD CONSTRAINT FK_DB021E96E92F8F78 FOREIGN KEY (recipient_id) REFERENCES users (id);
ALTER TABLE users_roles ADD CONSTRAINT FK_51498A8EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE users_roles ADD CONSTRAINT FK_51498A8ED60322AC FOREIGN KEY (role_id) REFERENCES roles (id);

